name: Daily Digest

on:
  workflow_dispatch:
  schedule:
    - cron: '57 0 * * *'

permissions:
  contents: write

jobs:
  digest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Step1
        run: |
          DATE=$(date +%Y-%m-%d)
          echo "DATE=${DATE}" >> $GITHUB_ENV

      - name: Step2
        run: echo "test"

      - name: Commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --staged --quiet || git commit -m "test"
          git push
